mode: predict
debug: False
load_ckpt: checkpoint_selection_straightpcf/best_checkpoint.pkl

components:
  data: predict
  transform: predict
  system: straightpcf
  model: straightpcf

writer:
  __target__: vm
  save_dir: results
  save_name: denoised
