mode: train
debug: False

components:
  data: train_cached
  transform: straightpcf
  system: straightpcf
  model: straightpcf

loss:
  loss: 1.0

optimizer:
  __target__: adam
  lr: 0.0001

trainer:
  epochs: 100
